import Head from "next/head";
import HomeComponent from "@/components/Home";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <div className="container flex flex-col gap-12">
          {/* <h1 className="text-5xl font-extrabold tracking-tight text-white sm:text-[5rem]">
            Welcome {session?.user.name}
          </h1> */}
          <HomeComponent />
        </div>
      </main>
    </>
  );
}
